### ISSUE TITLE
Override tab is not displayed in the N-panel

### ISSUE THREAD

**Issue by RustyR1ng** [Korchy/blender_eevee_materials_override#1]
![image_2022-03-18_13-58-29](https://user-images.githubusercontent.com/60072440/158991148-bc8ac786-ce82-4cc9-9c5d-39f3ca3a8f81.png)
**Blender Version - 3.0.1**

**Comment by Korchy** [comment]
HI!

Do you have any error messages in system console (main menu - window - toggle system console) ?

**Comment by RustyR1ng** [comment]
Hello! In the console, I see only one line about the addon: 

> It seems you are trying to use the dev version of the eevee_materials_override add-on. It may work not properly. Please download and use the release version!

**Comment by Korchy** [comment]
So you are using the dev version. Download he release from BM or Gumroad and use it.
https://b3d.interplanety.org/en/blender-add-on-eevee-materials-override/

**Comment by RustyR1ng** [comment]
Thank you!
Btw I just found your repository, but I didn't find any links to release packages or anything like that. Please add links to the repository because the first output in the search for "eevee material override" is your repository.

**Comment by Korchy** [comment]
Thank you for the feedback! I will update the readme in future.
