### ISSUE TITLE
No interface, no errors - Had to manually disable "dev_mode"

### ISSUE THREAD

**Issue by ecker00** [Korchy/blender_eevee_materials_override#2]
Enabling the add-on, noting happens. Get no tab and panel in the N-Panel. Had to modify `cfg.json`  and set `dev_mode` to `false`, then suddenly everything worked.

_**cfg.json**_
```json
{
    "dev_mode": false
}
```

Tested in both Blender 2.93 and 3.1

**Comment by Korchy** [comment]
Dev mode means that this is a developing version, it could be changed/modified/updated anytime and could not to work properly or at all. You do this on your own risk. Get the release versions from the Gumroad or Blender Market.

**Comment by ecker00** [comment]
Ah, sorry didn't realise that this source was not considered the "release". They looked the same at first glance.

**Comment by Korchy** [comment]
Sometimes they are the same. But in the developing versions could be some changes, that can disbalance the add-on work. Until the dev version and the release version will be synchronized. And so on.
