### ISSUE TITLE
Not working on 3.1.2

### ISSUE THREAD

**Issue by baldyman01** [Korchy/blender_eevee_materials_override#3]
Installed on 3.1.2 on Ubuntu 21.04. Override tab does not get added to the N-panel.
![Screenshot from 2022-04-15 17-54-07](https://user-images.githubusercontent.com/33987743/163598734-652ed48c-0947-46b4-84d0-9ba511be087f.png)

**Comment by Korchy** [comment]
From where do you get the distributive? Get the release version from the Gumroad or Blender Market.
